#!/usr/bin/env node

/**
 * Pre-build script for v0 Sandbox
 * This script:
 * 1. Cleans .next and .prisma folders (old compiled artifacts)
 * 2. Ensures MYSQL_URL from environment variables is properly set before Prisma generates the client
 * 3. Regenerates Prisma Client with the correct database URL
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

console.log('[BUILD-ENV] Starting pre-build environment setup...');

// Clean build artifacts
console.log('[BUILD-ENV] Cleaning build artifacts...');
const nextDir = path.join(__dirname, '..', '.next');
const prismaDir = path.join(__dirname, '..', 'node_modules', '.prisma');

[nextDir, prismaDir].forEach(dir => {
  if (fs.existsSync(dir)) {
    console.log('[BUILD-ENV] Removing:', dir);
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

console.log('[BUILD-ENV] Build artifacts cleaned\n');

// Get env vars from process
const MYSQL_URL = process.env.MYSQL_URL;
const DATABASE_URL = process.env.DATABASE_URL;

console.log('[BUILD-ENV] Environment variables:');
console.log('[BUILD-ENV] - MYSQL_URL:', MYSQL_URL ? `${MYSQL_URL.substring(0, 30)}...` : 'NOT SET');
console.log('[BUILD-ENV] - DATABASE_URL:', DATABASE_URL ? `${DATABASE_URL.substring(0, 30)}...` : 'NOT SET');

// Create or update .env.local with the public URL
const envLocalPath = path.join(__dirname, '..', '.env.local');
const dbUrl = MYSQL_URL || DATABASE_URL;

if (dbUrl) {
  console.log('[BUILD-ENV] Creating .env.local with database URL...');
  const envContent = `# Auto-generated by pre-build script
# These variables are required for Prisma client generation
MYSQL_URL="${dbUrl}"
DATABASE_URL="${dbUrl}"
NODE_ENV="development"
`;
  
  try {
    fs.writeFileSync(envLocalPath, envContent, 'utf8');
    console.log('[BUILD-ENV] ✓ .env.local updated successfully');
    console.log('[BUILD-ENV] Database URL set to:', dbUrl.substring(0, 50) + '...');
    
    // Regenerate Prisma Client with new URL
    console.log('[BUILD-ENV] Regenerating Prisma Client...');
    try {
      execSync('npx prisma generate', { 
        stdio: 'inherit',
        env: { ...process.env, MYSQL_URL: dbUrl }
      });
      console.log('[BUILD-ENV] ✓ Prisma Client regenerated successfully');
    } catch (prismaError) {
      console.warn('[BUILD-ENV] ⚠️  Prisma generation had issues, continuing...');
    }
  } catch (error) {
    console.error('[BUILD-ENV] ✗ Failed to update environment:', error.message);
    process.exit(1);
  }
} else {
  console.warn('[BUILD-ENV] ⚠️  No MYSQL_URL or DATABASE_URL found in environment');
  console.warn('[BUILD-ENV] Using existing .env.local');
  
  // Check if .env.local exists and warn if not
  if (!fs.existsSync(envLocalPath)) {
    console.warn('[BUILD-ENV] ⚠️  .env.local does not exist');
    console.warn('[BUILD-ENV] Please add MYSQL_URL to your v0 Vars');
  }
}

console.log('[BUILD-ENV] Pre-build setup completed\n');
